import "./globals.css";
import "@radix-ui/themes/styles.css";
import { ClerkProvider } from "@clerk/nextjs";

import { Theme } from "@radix-ui/themes";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <Theme>{children}</Theme>
        </body>
      </html>
    </ClerkProvider>
  );
}
